# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: file_service.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'file_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x66ile_service.proto\x12\x0c\x66ile_service\"6\n\x11UploadFileRequest\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\x0c\"%\n\x12UploadFileResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"\"\n\x0eGetFileRequest\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\"9\n\x0fGetFileResponse\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\x0c\x12\x15\n\ris_last_chunk\x18\x02 \x01(\x08\x32\xaa\x01\n\x0b\x46ileService\x12Q\n\nUploadFile\x12\x1f.file_service.UploadFileRequest\x1a .file_service.UploadFileResponse(\x01\x12H\n\x07GetFile\x12\x1c.file_service.GetFileRequest\x1a\x1d.file_service.GetFileResponse0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'file_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_UPLOADFILEREQUEST']._serialized_start=36
  _globals['_UPLOADFILEREQUEST']._serialized_end=90
  _globals['_UPLOADFILERESPONSE']._serialized_start=92
  _globals['_UPLOADFILERESPONSE']._serialized_end=129
  _globals['_GETFILEREQUEST']._serialized_start=131
  _globals['_GETFILEREQUEST']._serialized_end=165
  _globals['_GETFILERESPONSE']._serialized_start=167
  _globals['_GETFILERESPONSE']._serialized_end=224
  _globals['_FILESERVICE']._serialized_start=227
  _globals['_FILESERVICE']._serialized_end=397
# @@protoc_insertion_point(module_scope)
